/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_NDKExam */

#ifndef _Included_org_example_ndk_NDKExam
#define _Included_org_example_ndk_NDKExam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_NDKExam
 * Method:    getProcessInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_ndk_NDKExam_getProcessInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
